;this file for FamiTone2 library generated by text2data tool

title2_music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cb,$c5,$00,$01
@env2:
	.byte $cb,$c1,$00,$01


@song0ch0:
	.byte $fb,$0b
@song0ch0loop:
@ref0:
	.byte $00,$9d
@ref1:
	.byte $9f
@ref2:
	.byte $9f
@ref3:
	.byte $9f
@ref4:
	.byte $80,$24,$3c,$54,$24,$3c,$54,$24,$3c,$22,$3a,$52,$22,$3a,$52,$22
	.byte $3a
@ref5:
	.byte $28,$40,$58,$28,$40,$58,$28,$40,$74,$5c,$44,$2c,$14,$2c,$44,$5c
@ref6:
	.byte $24,$3c,$54,$24,$3c,$54,$24,$3c,$22,$3a,$52,$22,$3a,$52,$22,$3a
	.byte $ff,$10
	.word @ref5
@ref8:
	.byte $74,$5c,$44,$74,$5c,$44,$74,$5c,$78,$60,$48,$78,$60,$48,$78,$60
@ref9:
	.byte $7e,$66,$4e,$7e,$66,$4e,$7e,$66,$24,$4e,$1e,$4a,$1a,$4a,$1a,$44
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref10:
	.byte $80,$1e,$36,$4e,$1e,$36,$4e,$1e,$36,$1a,$32,$4a,$1a,$32,$4a,$1a
	.byte $32
@ref11:
	.byte $22,$3a,$52,$22,$3a,$52,$22,$3a,$6c,$54,$3c,$24,$0c,$24,$3c,$54
@ref12:
	.byte $1e,$36,$4e,$1e,$36,$4e,$1e,$36,$1a,$32,$4a,$1a,$32,$4a,$1a,$32
	.byte $ff,$10
	.word @ref11
	.byte $ff,$10
	.word @ref12
	.byte $ff,$10
	.word @ref11
	.byte $ff,$10
	.word @ref12
	.byte $ff,$10
	.word @ref11
@ref18:
	.byte $6c,$54,$3c,$6c,$54,$3c,$6c,$54,$70,$58,$40,$70,$58,$40,$70,$58
@ref19:
	.byte $74,$5c,$44,$74,$5c,$44,$74,$5c,$2c,$58,$28,$54,$24,$52,$22,$4e
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref20:
	.byte $00,$9d
@ref21:
	.byte $9f
@ref22:
	.byte $82,$4f,$00,$4e,$00,$4e,$00,$36,$4b,$00,$4a,$00,$4a,$00,$4a
@ref23:
	.byte $53,$00,$52,$00,$52,$00,$52,$54,$3c,$54,$3c,$54,$3c,$54,$3c
@ref24:
	.byte $4f,$00,$4e,$00,$4e,$00,$36,$4b,$00,$4a,$00,$4a,$00,$4a
	.byte $ff,$0f
	.word @ref23
	.byte $ff,$0e
	.word @ref24
	.byte $ff,$0f
	.word @ref23
@ref28:
	.byte $80,$54,$87,$00,$54,$00,$58,$87,$00,$58,$00
@ref29:
	.byte $5c,$87,$00,$5c,$01,$58,$00,$54,$00,$52,$00,$4e
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref30:
	.byte $9f
@ref31:
	.byte $9f
@ref32:
	.byte $9f
@ref33:
	.byte $9f
@ref34:
	.byte $9f
@ref35:
	.byte $9f
@ref36:
	.byte $9f
@ref37:
	.byte $9f
@ref38:
	.byte $9f
@ref39:
	.byte $9f
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref40:
	.byte $9f
@ref41:
	.byte $9f
@ref42:
	.byte $9f
@ref43:
	.byte $9f
@ref44:
	.byte $9f
@ref45:
	.byte $9f
@ref46:
	.byte $9f
@ref47:
	.byte $9f
@ref48:
	.byte $9f
@ref49:
	.byte $9f
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$04
@song1ch0loop:
@ref50:
	.byte $cb
@ref51:
	.byte $cb
@ref52:
	.byte $cb
@ref53:
	.byte $cb
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref54:
	.byte $80,$1b,$00,$87,$1b,$00,$91,$1b,$00,$87,$1b,$00,$83,$1b,$00,$87
@ref55:
	.byte $1f,$00,$87,$1f,$00,$91,$1f,$00,$87,$1f,$00,$83,$1f,$00,$87
@ref56:
	.byte $1b,$00,$87,$1b,$00,$91,$1b,$00,$87,$1b,$00,$83,$1b,$00,$87
@ref57:
	.byte $1f,$00,$87,$1b,$00,$b7
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref58:
	.byte $80,$36,$87,$01,$36,$85,$00,$32,$83,$00,$85,$36,$87,$01,$36,$87
	.byte $33,$3d,$3a,$83
@ref59:
	.byte $36,$87,$01,$36,$85,$00,$32,$83,$00,$85,$36,$87,$01,$36,$87,$33
	.byte $3d,$3a,$83
	.byte $ff,$13
	.word @ref59
@ref61:
	.byte $36,$9f,$33,$45,$41,$3c,$83,$41,$3d,$3a,$83,$3d,$3a,$83
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref62:
	.byte $cb
@ref63:
	.byte $cb
@ref64:
	.byte $cb
@ref65:
	.byte $cb
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref66:
	.byte $cb
@ref67:
	.byte $cb
@ref68:
	.byte $cb
@ref69:
	.byte $cb
	.byte $fd
	.word @song1ch4loop
